#!/usr/bin/env bash
# install.sh - KB workflow one-click installer
#
# Usage:
#   curl -fsSL <url>/install.sh | bash              # install from GitHub
#   ./install.sh                                    # install from current dir (local dev)
#   ./install.sh /path/to/local/repo                # install from specific local path
#
# What it does:
#   1. Detects source (local path or GitHub clone)
#   2. Creates ~/.claude/kb/ structure
#   3. Symlinks CLI to ~/.local/bin/kb-workflow
#   4. Symlinks SKILL.md to ~/.claude/skills/kb-workflow/
#   5. Generates config.local.yaml if missing
#   6. Runs capability detection
#   7. Prints status banner

set -euo pipefail

# ---------- config ----------
GITHUB_REPO="${KB_WORKFLOW_REPO:-https://github.com/kongshan001/kb-workflow.git}"
WORKFLOW_HOME="${KB_WORKFLOW_HOME:-$HOME/kb-workflow}"
KB_ROOT="${KB_ROOT:-$HOME/.claude/kb}"
SKILL_DIR="$HOME/.claude/skills/kb-workflow"
LOCAL_BIN="$HOME/.local/bin"

# ---------- helpers ----------
log() { printf '%b\n' "$*"; }
ok()  { log "  ✅ $*"; }
warn(){ log "  ⚠️  $*"; }
fail(){ log "  ❌ $*"; exit 1; }

# ---------- preflight ----------
command -v git   >/dev/null 2>&1 || fail "git is required but not installed"
command -v bash >/dev/null 2>&1 || fail "bash is required"

# ---------- 1. detect source ----------
SOURCE_PATH=""
if [[ -n "${1:-}" ]]; then
  # explicit local path
  SOURCE_PATH="$(cd "$1" && pwd)"
  log "📦 Local install from: $SOURCE_PATH"
elif [[ -f "./SKILL.md" && -f "./bin/kb-workflow" ]]; then
  # running from inside the repo
  SOURCE_PATH="$(pwd)"
  log "📦 Local install from: $SOURCE_PATH"
else
  # clone from GitHub
  log "📥 Cloning from GitHub: $GITHUB_REPO"
  if [[ -d "$WORKFLOW_HOME" ]]; then
    log "   existing $WORKFLOW_HOME found, pulling latest"
    git -C "$WORKFLOW_HOME" pull --ff-only || warn "pull failed, using existing"
  else
    git clone --depth 1 "$GITHUB_REPO" "$WORKFLOW_HOME" \
      || fail "clone failed — set KB_WORKFLOW_REPO env or pass local path"
  fi
  SOURCE_PATH="$WORKFLOW_HOME"
fi

[[ -f "$SOURCE_PATH/SKILL.md" ]]         || fail "SKILL.md not found in $SOURCE_PATH"
[[ -x "$SOURCE_PATH/bin/kb-workflow" ]]  || fail "bin/kb-workflow not executable in $SOURCE_PATH"
ok "source ready: $SOURCE_PATH"

# ---------- 2. create KB root ----------
mkdir -p "$KB_ROOT/entries" "$KB_ROOT/external"
ok "KB root: $KB_ROOT"

# ---------- 3. symlink CLI ----------
mkdir -p "$LOCAL_BIN"
ln -sf "$SOURCE_PATH/bin/kb-workflow" "$LOCAL_BIN/kb-workflow"
ok "CLI: $LOCAL_BIN/kb-workflow → $SOURCE_PATH/bin/kb-workflow"

# ensure ~/.local/bin is on PATH for this session
case ":$PATH:" in
  *":$LOCAL_BIN:"*) ;;
  *) warn "$LOCAL_BIN not in PATH; add it to your shell rc" ;;
esac

# ---------- 4. symlink Skill ----------
mkdir -p "$HOME/.claude/skills" "$SKILL_DIR"
ln -sf "$SOURCE_PATH/SKILL.md"   "$SKILL_DIR/SKILL.md"
ln -sf "$SOURCE_PATH/config"     "$SKILL_DIR/config"
[[ -f "$SOURCE_PATH/CHANGELOG.md" ]] && ln -sf "$SOURCE_PATH/CHANGELOG.md" "$SKILL_DIR/CHANGELOG.md"
ok "Skill: $SKILL_DIR"

# ---------- 5. config.local.yaml ----------
if [[ ! -f "$KB_ROOT/config.local.yaml" ]]; then
  cat > "$KB_ROOT/config.local.yaml" <<EOF
# Generated by kb-workflow install on $(date +%Y-%m-%d)
# Override values from defaults.yaml. See SKILL.md for full list.

# kb_root: $KB_ROOT

# topics:
#   add: []       # extra topics to whitelist (merged with defaults)
#   remove: []    # topics to disable on this device
EOF
  ok "config.local.yaml created"
else
  ok "config.local.yaml exists, keeping"
fi

# ---------- 6. _state.md ----------
if [[ ! -f "$KB_ROOT/_state.md" ]]; then
  cat > "$KB_ROOT/_state.md" <<EOF
# KB Runtime State

> Assistant-owned. Harness 不读此文件，每次会话开场由 assistant 主动 Read 一次。

last_updated: $(date +%Y-%m-%d)
last_review: null
last_capture: null

---

## ⚠️ 待裁定
> 空

## 🟡 Tentative Open
> 空

## 最近 10 条收录
> 空

## 主题触发 (topic → palace room)
> see config/topics.yaml

## 统计
- entries/: 0
- external/: 0
- 待裁定: 0
- tentative open: 0
EOF
  ok "_state.md created"
else
  ok "_state.md exists, keeping"
fi

# ---------- 7. capability detection ----------
if [[ -x "$SOURCE_PATH/scripts/capability-detect.sh" ]]; then
  log ""
  log "🔍 Capability detection:"
  "$SOURCE_PATH/scripts/capability-detect.sh" | sed 's/^/  /'
fi

# ---------- 7.5. cron registration (D7) ----------
if command -v cc-connect >/dev/null 2>&1; then
  log ""
  log "⏰ Registering /kb-review weekly cron (Sunday 18:00, summary only)..."
  # idempotent: cc-connect cron add returns error if exists; we tolerate
  if cc-connect cron add \
      --cron "0 18 * * 0" \
      --prompt "/kb-review summary" \
      --desc "kb-workflow weekly summary" \
      2>/dev/null; then
    ok "cron registered (Sunday 18:00)"
  else
    ok "cron already registered (skipped)"
  fi
else
  warn "cc-connect not available; skip cron registration"
  warn "to enable later: cc-connect cron add --cron '0 18 * * 0' --prompt '/kb-review summary'"
fi

# ---------- 8. record installed source ----------
echo "$SOURCE_PATH" > "$KB_ROOT/.installed_source"

# ---------- 9. banner ----------
log ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅ KB workflow installed"
log "   workflow: $SOURCE_PATH"
log "   kb_root:  $KB_ROOT"
log "   cli:      $LOCAL_BIN/kb-workflow"
log "   skill:    $SKILL_DIR"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log ""
log "Next:"
log "  kb-workflow status        # check current state"
log "  Start a new Claude session to load the Skill"
log "  /kb-review                # trigger a review (inside Claude)"
log ""
log "Weekly review (Sunday 18:00) is registered via cc-connect cron"
log "if available. Disable: cc-connect cron del <job-id>"
